name: Model Training

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train_model.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: ./model.pkl
